### ISSUE TITLE
API

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen-server#2]
I think we need 2 endpoints:

- `POST /audio`.  
This is where you upload a track.  It returns a URL that you can poll to see if your analysis is done.

- `GET /analysis?id=<some-id>`
This is where you poll to see if your analysis is done.  It returns some sort of `50%` data if your analysis is still pending, and returns the actual analysis JSON once it is done.  If we decide to host audio on S3, the S3 url is in the analysis JSON.

**Comment by alnesbit** [comment]
This makes sense to me from a high-level perspective and matches my recollection of the principles of using `track/upload`. I haven't yet made any attempt to analyze compatability in detail, but this compatibility can be refined as we move forward, of course.
